---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-notification-service
  namespace: app-notification-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: notification-worker
  policyTypes:
  - Ingress
  - Egress
  # No ingress allowed for worker
  egress:
  # Allow DNS resolution
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow Service Bus (5671, 443)
  - ports:
    - protocol: TCP
      port: 5671
    - protocol: TCP
      port: 443
