replicaCount: 1

image:
  repository: acrhealthsyncdev.azurecr.io/patient-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "b68a5c0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations:
    # Workload identity annotation. Will be replaced by CI/CD if needed.
    azure.workload.identity/client-id: "a137e829-3aa6-4aa8-80cb-a0c091cfe900"
  name: "patient-service-sa"

podAnnotations: {}
podLabels:
  azure.workload.identity/use: "true"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

keyvault:
  name: kv-hsync-r4lanj
  tenantId: "ecd8c5a8-1729-4bc9-8fa7-78a7ce2919b8"
  sqlSecretName: db-connection-string
  serviceBusSecretName: servicebus-connection-string
