apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: billing-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/thimanshu756/healthsync.git'
    path: platform/charts/billing-service
    targetRevision: feature/phase1-core-infra
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-billing-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
