apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: healthsync
spec:
  project: default
  source:
    repoURL: https://github.com/thimanshu756/healthsync.git
    targetRevision: feature/phase1-core-infra
    path: platform/charts/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
